### ISSUE TITLE
Documentation fails to compile with Sphinx > 1.7.0

### ISSUE THREAD

**Issue by daniellivingston** [amanzi/amanzi#350]
When running `make html` in `$AMANZI_DIR/doc/web_front`, an error is thrown:

```
Could not import extension sphinxcontrib.autorun (exception: cannot import name Directive)
make[1]: *** [html-ssl-set] Error 2
make: *** [html] Error 2
```

`Directive` was deprecated as of Sphinx 1.7.0 (see: https://github.com/readthedocs/readthedocs.org/issues/4057).

Running the following resolved the issue:

```
pip uninstall sphinx
pip install sphinx==1.6.7
```

Somewhat unrelated, but trying to install `sphinxcontrib-bibtex` (for `doc/user_guide`) fails with:

```
~/.bin/amanzi/doc/user_guide master* ⇣
(py2) ❯ pip install sphinxcontrib-bibtex
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting sphinxcontrib-bibtex
  Using cached https://files.pythonhosted.org/packages/96/10/ba1498a1c2d7a47a4ce904198989fdbceb0b00057d2e5ff666149e7beb67/sphinxcontrib-bibtex-1.0.0.tar.gz
Collecting pybtex>=0.20 (from sphinxcontrib-bibtex)
  Using cached https://files.pythonhosted.org/packages/94/2a/11039970561f1bbc74fbaca89b59c26b398a0a70bba8caad553ac779b4f7/pybtex-0.22.2-py2.py3-none-any.whl
Collecting pybtex-docutils>=0.2.0 (from sphinxcontrib-bibtex)
  Using cached https://files.pythonhosted.org/packages/e9/97/066aa09efc1a1f969ffc6ca0e697787a3b8eb9e847a9b5973c0f73119318/pybtex_docutils-0.2.2-py2.py3-none-any.whl
Collecting Sphinx>=2.0 (from sphinxcontrib-bibtex)
  ERROR: Could not find a version that satisfies the requirement Sphinx>=2.0 (from sphinxcontrib-bibtex) (from versions: 0.1.61611, 0.1.61798, 0.1.61843, 0.1.61945, 0.1.61950, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.5, 0.5.1, 0.5.2b1, 0.5.2, 0.6b1, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 1.0b1, 1.0b2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.2b1, 1.2b2, 1.2b3, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3b1, 1.3b2, 1.3b3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.4a1, 1.4b1, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5a1, 1.5a2, 1.5b1, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6b1, 1.6b2, 1.6b3, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.7.0b1, 1.7.0b2, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.8.0b1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5)
ERROR: No matching distribution found for Sphinx>=2.0 (from sphinxcontrib-bibtex)
```

Sphinx-1.8.5 appears to be the latest Sphinx version available for Python 2.x. Switching to Python 3.6 (where I'm running Sphinx v2.2.0) allows me to install this package, but `make html` fails with:

```
Running Sphinx v2.2.0
WARNING: Support for evaluating Python 2 syntax is deprecated and will be removed in Sphinx 4.0. Convert /Users/livingston/.bin/amanzi/doc/user_guide/conf.py to Python 3 syntax.

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/anaconda3/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/livingston/.bin/amanzi/doc/user_guide/conf.py", line 95, in <module>
    amanzi_latest_tag_ver=amanzi_latest_tag.replace('amanzi-','')
TypeError: a bytes-like object is required, not 'str'

make: *** [html] Error 2
```

**Comment by lipnikov** [comment]
Works for me on Ubuntu with anaconda2/2019.03 and Sphinx/1.8.5 after I comment out tikz and autorun extensions.

**Comment by daniellivingston** [comment]
Addressed in pull-request #354 .

**Comment by jd-moulton** [comment]
I would like to keep autorun around if possible as its a template for how I'd like to launch runs from within a document directive.  I'd like to separate the execution of the tests with the plotting of the results.   

For what it's worth I don't have any trouble on sphinx 1.7.9 with autorun.  I use sphinx from anaconda, but install the extra contributed packages with pip.  

`pn1806419:~ moulton$ conda list sphinx`
`# packages in environment at /local/anaconda/anaconda2-5.3.0:`
`#`
`# Name                              Version                          Build  Channel`
`sphinx                                   1.7.9                                 py27_0`
`sphinxcontrib                        1.0                                   py27_1`
`sphinxcontrib-autorun          0.1.post20140415           <pip>`
`sphinxcontrib-bibtex             0.4.0                               <pip>`
`sphinxcontrib-tikz                  0.4.6                              <pip>`
`sphinxcontrib-websupport    1.1.0                               py27_1`

The page you pointed to about the contributed autorun package being deprecated doesn't seem to apply. Please try to rebuild with all of the required contributed packages installed.
