### ISSUE TITLE
Compulation error in CCSE 

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#297]
gcc-7.2.0 discovered this error:
 
.../build-tpls/build/tpls/ccse/ccse-1.3.4-source/Src/C_BaseLib/ArrayLim.H:31:29: error: taking address of temporary array
 #define BCREC_3D(x) (int []){x[0], x[1], 0, x[2], x[3], 0}

Our patch is incorrect. Any suggestions besides using std::vector\<int\> in place of int [], followed by taking address of 0-th component?

**Comment by ecoon** [comment]
Is that a recent patch change?  My source (after patching) reads:

`#define BCREC_3D(x) &((int []){x[0], x[1], 0, x[2], x[3], 0}[0])`

but I would have thought that your version, 

#define BCREC_3D(x) (int []){x[0], x[1], 0, x[2], x[3], 0}

would work.  Note that I don't think a std::vector would fix it, as the vector would be just as temporary as the int[]...


`

**Comment by lipnikov** [comment]
std::vector<int> worked with gcc 7.2

**Comment by lipnikov** [comment]
Still failing

**Comment by lipnikov** [comment]
Fixed on a branch, see #432
